

version: "3"

services:
  mongo:
    container_name: pest-detection-mongo
    image: mongo:latest
    restart: unless-stopped
    ports: 
      - 27017:27017
    volumes:
      - ../../db/mongo_data:/data/db
    
  client:
    container_name: pest-detection-client
    image: arpitgo4/alpine-node
    restart: unless-stopped
    working_dir: /usr/src/app
    volumes:
      - ../../client:/usr/src/app
    command: sh -c "npm install && npm run start:development"
    expose: 
      - 3000
    depends_on:
      - server
      - api_gateway
    environment:
      - API_GATEWAY=localhost
    
  server: 
    container_name: pest-detection-server
    image: arpitgo4/alpine-node
    restart: unless-stopped
    working_dir: /usr/src/app
    volumes:
      - ../../server:/usr/src/app
      - ../../pest-detection-uploads:/usr/src/app/static/uploads
    command: sh -c "npm install && npm run start:development"
    expose:
      - 8080
    depends_on:
      - mongo
      - api_gateway
    environment:
      - SERVER_PORT=8080
      - NODE_ENV=development
      - JWT_SECRET=U5ZnTwt0tpmUHAVhES51iXM52mFSbxsOojFs5JNnZUv082ZACjnsuRNklomA
      - JWT_HEADER=x-token
      - MONGO_HOST=mongo:27017
      - MONGO_DATABASE=pest-detection-app
      - API_GATEWAY=localhost

  api_gateway:
    container_name: pest-detection-api-gateway
    image: pest-detection-api-gateway
    build: ../../api-gateway
    restart: unless-stopped
    ports:
      - 80:80